apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: solace-catalog
  namespace: olm
spec:
  sourceType: grpc
  image: ghcr.io/solacedev/pubsubplus-eventbroker-operator-v1alpha1-catalog:latest
  secrets:
  - regcred
  displayName: Solace Catalog
  publisher: Solace
  updateStrategy:
    registryPoll:
      interval: 1m
