apiVersion: pubsubplus.solace.com/v1alpha1
kind: PubSubPlusEventBroker
metadata:
  name: test1
spec:
  redundancy: true
  developer: true
  timezone: UTC
  extraEnvVars:
    - name: env_variable_name
      value: "env_variable_value"
  extraEnvVarsCM: my-cluster-extra-env-configmap #ensure configmap exists with this name
  extraEnvVarsSecret: my-cluster-extra-env-secret #ensure secret exists with this name
  podDisruptionBudgetForHA: false
  image:
    repository: solace/solace-pubsub-standard
    tag: latest
    pullPolicy: IfNotPresent
  nodeAssignment:
    - name: Primary
      spec:
        affinity:
          podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: instance
                  operator: In
                  values:
                  - test1
              topologyKey: "kubernetes.io/hostname"
        nodeSelector: {}
    - name: Backup
      spec:
        affinity: {}
        nodeSelector: {}
    - name: Monitor
      spec:
        affinity: {}
        nodeSelector: {}
  securityContext:
    enabled: true
    fsGroup: 1000002
    runAsUser: 1000001
  serviceAccount:
    name: default #ensure serviceAccount exists with this name in the same namespace
  tls:
    enabled: false
  service:
    type: LoadBalancer
    annotations: {}
    ports:
      - servicePort: 2222
        containerPort: 2222
        protocol: TCP
        name: tcp-ssh
      - servicePort: 8080
        containerPort: 8080
        protocol: TCP
        name: tcp-semp
      - servicePort: 1943
        containerPort: 1943
        protocol: TCP
        name: tls-semp
      - servicePort: 55555
        containerPort: 55555
        protocol: TCP
        name: tcp-smf
      - servicePort: 55003
        containerPort: 55003
        protocol: TCP
        name: tcp-smfcomp
      - servicePort: 55443
        containerPort: 55443
        protocol: TCP
        name: tls-smf
      - servicePort: 55556
        containerPort: 55556
        protocol: TCP
        name: tcp-smfroute
      - servicePort: 8008
        containerPort: 8008
        protocol: TCP
        name: tcp-web
      - servicePort: 1443
        containerPort: 1443
        protocol: TCP
        name: tls-web
      - servicePort: 9000
        containerPort: 9000
        protocol: TCP
        name: tcp-rest
      - servicePort: 9443
        containerPort: 9443
        protocol: TCP
        name: tls-rest
      - servicePort: 5672
        containerPort: 5672
        protocol: TCP
        name: tcp-amqp
      - servicePort: 5671
        containerPort: 5671
        protocol: TCP
        name: tls-amqp
      - servicePort: 1883
        containerPort: 1883
        protocol: TCP
        name: tcp-mqtt
      - servicePort: 8883
        containerPort: 8883
        protocol: TCP
        name: tls-mqtt
      - servicePort: 8000
        containerPort: 8000
        protocol: TCP
        name: tcp-mqttweb
      - servicePort: 8443
        containerPort: 8443
        protocol: TCP
        name: tls-mqttweb
  storage:
    slow: false
    messagingNodeStorageSize: 30Gi
    monitorNodeStorageSize: 2Gi
    customVolumeMount:
      - name: Primary
        persistentVolumeClaim:
          claimName: my-primary-pvc-name
      - name: Backup
        persistentVolumeClaim:
          claimName: my-backup-pvc-name
      - name: Monitor
        persistentVolumeClaim:
          claimName: my-monitor-pvc-name
    useStorageClass: standard
  monitoring:
    enabled: true
    image:
      repository: ghcr.io/solacedev/solace_prometheus_exporter
      tag: sol-76199
      pullPolicy: Always
      pullSecrets:
      - name: regcred