---
apiVersion: pubsubplus.solace.com/v1alpha1
kind: PubSubPlusEventBroker
metadata:
  name: test-nonha
spec:
  redundancy: false
  developer: true
  timezone: UTC
  tls:
    enabled: false
  image: {}
  securityContext: {}
  monitoring:
    enabled: true
    image:
      repository: ghcr.io/solacedev/solace_prometheus_exporter
      tag: sol-76199
      pullPolicy: Always
      pullSecretName:
      - name: regcred