---
apiVersion: pubsubplus.solace.com/v1alpha1
kind: PubSubPlusEventBroker
metadata:
  name: test-nonha
spec:
  redundancy: false
  developer: true
  timezone: UTC
  extraEnvVars:
    - name: TestType
      value: "GithubAction"
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  podDisruptionBudgetForHA: false
  image: {}
#  nodeAssignment: {}
  securityContext: {}
  tls:
    enabled: true
    serverTlsConfigSecret: test-tls
  service: {}
  monitoring:
    enabled: true
    listenTLS: false
    image:
      repository: ghcr.io/solacedev/solace_prometheus_exporter
      tag: sol-76199
      pullPolicy: Always
      pullSecretName:
      - name: regcred