name: Build and Test

on:
  push:

jobs:
  build:
    name: Build & push image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: make docker-build

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push GitHub Container Registry
        run: make docker-push


  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v1

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Testing operator deployment
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          kubectl create ns pubsubplus-v1alpha1-system
          kubectl create secret generic regcred --from-file=.dockerconfigjson=${HOME}/.docker/config.json --type=kubernetes.io/dockerconfigjson -n pubsubplus-v1alpha1-system
          make deploy | grep created
          kubectl rollout status deployment pubsubplus-v1alpha1-controller-manager -n pubsubplus-v1alpha1-system --timeout=30s
          kubectl get crd | grep eventbrokers

      - name: Testing the Operator - nonHA
        run: |
          kubectl apply -f ci/manifests/eventbroker-nonha.yaml | grep "test-nonha created"
          sleep 5 ; kubectl get all
          kubectl wait pods --selector app.kubernetes.io/instance=test-nonha --for condition=Ready --timeout=120s
          kubectl get po --show-labels | grep test-nonha | grep "1/1"
          kubectl get po --show-labels | grep test-nonha | grep active=true
          kubectl get sts | grep test-nonha
          kubectl port-forward svc/test-nonha-pubsubplus 8080:8080 &
          sleep 1
          kubectl port-forward svc/test-nonha-pubsubplus 55555:55555 &
          sleep 1
          curl localhost:8080 | grep aurelia
          curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64
          tar -xvf SDKPERF_C_LINUX64
          pubSubTools/sdkperf_c -cip=tcp://localhost:55555 -mn=1000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"
          sleep 50 ; kubectl get all
          kubectl wait pods --selector solace-prometheus-exporter=true --for condition=Ready --timeout=120s
          kubectl port-forward svc/test-nonha-pubsubplus-prometheus-exporter-service 9628:9628 &
          sleep 1
          curl localhost:9628 | grep Exporter
          kubectl delete eventbroker test-nonha | grep deleted
