name: Build and Test

on:
  push:

jobs:
  build:
    name: Build & push image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v1

      - name: Lint and Build
        run: |
          #go fmt ./... | wc -l | grep 0
          make docker-build

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push GitHub Container Registry
        run: make docker-push

  test-full-params:
    # if: ${{ false }}  # disable for now
    needs: build
    uses: ./.github/workflows/test-full-params.yml
    secrets: inherit

  test-helm-upgrade:
    # if: ${{ false }}  # disable for now
    needs: build
    uses: ./.github/workflows/test-helm-upgrade.yml
    secrets: inherit

  test-minimal-params:
    # if: ${{ false }}  # disable for now
    needs: build
    uses: ./.github/workflows/test-minimal-params.yml
    secrets: inherit

  test-minimal-params-ha:
    # if: ${{ false }}  # disable for now
    needs: build
    uses: ./.github/workflows/test-minimal-params-ha.yml
    secrets: inherit

  test-broker-upgrade-update:
    # if: ${{ false }}  # disable for now
    needs: build
    uses: ./.github/workflows/test-broker-upgrade-update.yml
    secrets: inherit