on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true
        default: '1.0.0-dev'

jobs:
  build_web:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Generate Third Party License
        run: |
          make generate-license

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v12
        id: verify-changed-files
        with:
          files: THIRD-PARTY-LICENSES.md

      - name: Commit changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add THIRD-PARTY-LICENSES.md
          git commit -m "chore: Updated third party license."

      - name: Push changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.ref }}

      - name: Run Whitesource Action
        uses: mercari/Whitesource-Scan-Action@v1.0.0
        with:
          wssURL: https://saas.whitesourcesoftware.com/agent
          apiKey: ${{ secrets.WSS_API_KEY }}
          productName: 'pubsubplus-kubernetes-operator'
          projectName: 'pubsubplus-kubernetes-operator'
          configFile: 'ci/whitesource/whitesource-agent.config'

      - name: Build and publish
        run: |
          export VERSION='${{ github.event.inputs.release_tag }}'
          make generate manifest
          make docker-build docker push
          make bundle
          make bundle-build bundle-push
          make catalog-build catalog-push
