on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true
        default: '1.0.0-dev'

jobs:
  build_web:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build and publish
        run: |
          export VERSION='${{ github.event.inputs.release_tag }}'
          make generate manifest
          make docker-build docker push
          make bundle
          make bundle-build bundle-push
          make catalog-build catalog-push
