name: Build and Test for Helm to Operator Upgrade

on: workflow_call

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Operator deployment
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          kubectl create ns pubsubplus-operator-system --save-config
          kubectl create secret generic regcred --from-file=.dockerconfigjson=${HOME}/.docker/config.json --type=kubernetes.io/dockerconfigjson -n pubsubplus-operator-system
          make deploy | grep created
          kubectl rollout status deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system --timeout=30s
          kubectl get crd | grep eventbrokers

      - name: Create nonHA deployment with image tag "latest"
        run: |
          kubectl apply -f ci/manifests/eventbroker-upgrade-update.yaml | grep "test-nonha-upgrade-update"
          sleep 5 ; kubectl get all
          kubectl wait pods --selector app.kubernetes.io/instance=test-nonha-upgrade-update --for condition=Ready --timeout=120s | grep "condition met"
          kubectl get po --show-labels | grep test-nonha-upgrade-update | grep "1/1"
          kubectl get po --show-labels | grep test-nonha-upgrade-update | grep active=true
          kubectl get sts | grep test-nonha-upgrade-update
          kubectl get svc | grep LoadBalancer
          kubectl port-forward svc/test-nonha-upgrade-update-pubsubplus 55555:55555 &
          sleep 5
          curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64
          tar -xvf SDKPERF_C_LINUX64
          pubSubTools/sdkperf_c -cip=tcp://localhost:55555 -mn=1000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"

      - name: Upgrade nonHA deployment to a compatible image tag - expecting automated uopgrade
        run: |
          REPO=solace/solace-pubsub-standard
          # grab a tag from Docker Hub that has the same SHA as "latest", so upgrade is easy
          DOCKERHUBRESULTS=`curl --silent "https://hub.docker.com/v2/repositories/$REPO/tags?page_size=1000" | jq -r '.results[] | "\(.digest) \(.name)"' | sort`
          SHA=`echo "$DOCKERHUBRESULTS" | grep latest | awk '{print $1;}'`
          UPGRADETAG=`echo "$DOCKERHUBRESULTS" | grep $SHA | head -n 1 | awk '{print $2;}'`; echo "Upgrade version: ${UPGRADETAG}"
          # overwrite the upgrade version, then apply manifest
          sed -i "s/latest/\"${UPGRADETAG}\"/" ci/manifests/eventbroker-upgrade-update.yaml
          kubectl apply -f ci/manifests/eventbroker-upgrade-update.yaml | grep "test-nonha-upgrade-update"
          sleep 10; kubectl get all
          while ! kubectl get po | grep "0/1" ; do sleep 1 ; done
          kubectl get all
          kubectl wait pods --selector app.kubernetes.io/instance=test-nonha-upgrade-update --for condition=Ready --timeout=120s | grep "condition met"
          kubectl get po --show-labels | grep test-nonha-upgrade-update | grep "1/1"
          kubectl get po --show-labels | grep test-nonha-upgrade-update | grep active=true
          kubectl get po -o yaml | grep "image: ${REPO}:${UPGRADETAG}"
          pkill -f "port-forward"; kubectl port-forward svc/test-nonha-upgrade-update-pubsubplus 55555:55555 &
          pubSubTools/sdkperf_c -cip=tcp://localhost:55555 -mn=1000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"

      - name: Update deployment service type - expecting automated update with no pod restart
        run: |
          # overwrite the service type, then apply manifest
          sed -i "s/LoadBalancer/NodePort/" ci/manifests/eventbroker-upgrade-update.yaml
          kubectl apply -f ci/manifests/eventbroker-upgrade-update.yaml | grep "test-nonha-upgrade-update"
          sleep 10; kubectl get all
          kubectl get svc -o yaml | grep NodePort
          pkill -f "port-forward"; kubectl port-forward svc/test-nonha-upgrade-update-pubsubplus 55555:55555 & 
          pubSubTools/sdkperf_c -cip=tcp://localhost:55555 -mn=1000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"

      - name: Delete broker deployment
        run: |
          # show any error in the operator logs
          kubectl logs $POD -n pubsubplus-operator-system | grep error || echo
          kubectl delete eventbroker test-nonha-upgrade-update | grep deleted
